server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hexapic_dev
    username: hexapic
    password: hexapicpwd

  devtools:
    restart:
      enabled: true

  jade4j:
    caching: false
    prettyPrint: true

flyway:
  baseline-on-migrate: true
  clean-on-validation-error: true