CREATE TABLE tag (
  id VARCHAR(255) NOT NULL,
  right_answers BIGINT NOT NULL DEFAULT 0,
  wrong_answers BIGINT NOT NULL DEFAULT 0,

  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,

  PRIMARY KEY(id)
);

CREATE TRIGGER update_user_updated_at BEFORE UPDATE ON tag
FOR EACH ROW EXECUTE PROCEDURE upd_datetime();